### ISSUE TITLE
Sitemap generator

### ISSUE THREAD

**Issue by andronasef** [sveltech/svelte-filerouter#397]

**Comment by ghostdevv** [comment]
Can you please provide more information other than "sitemap generator"? @andronasef

**Comment by andronasef** [comment]
I believe that tiny svelte framework that might be mush bigger thing in the future
So every site need a sitemap for seo so it would be better if routefiy has sitemap generator plugin

**Comment by ghostdevv** [comment]
@andronasef you are able to generate a sitemap by parsing the contents in the `.routify` folder, but there currently isn't a tool that exists to generate it for you

**Comment by HeyITGuyFixIt** [comment]
I created a plugin that solves this: [routify-plugin-sitemap](https://www.npmjs.com/package/routify-plugin-sitemap).
