### ISSUE TITLE
isActive not work in dynamic prefix url 

### ISSUE THREAD

**Issue by oschina** [sveltech/svelte-filerouter#405]
**bug description**
```
<script>
    const Menus = [
        { name: 'Overview',  href: '' },
        { name: 'Help',    href: 'help' },
        { name: 'Settings',    href: 'settings' }
    ];
    let appid = 'app1';
</script>
{#each Menus as option, i}
<a href="{$url('/:app/:href', {app:appid, href:option.href})}" class:active={$isActive('/:app/:href', {app:appid, href:option.href})} >{option.name}</a>
{/each}
```
The url like this: /app1/overview  ,  /app1/settings

**version**
Routify  2.18.3, Svelte 3.35.0

But the isActive always return false, how can i handle this problem ? 

Thx.

**Comment by jakobrosenberg** [comment]
Can you make a small reproducible on codesandbox to show this?

**Comment by jakobrosenberg** [comment]
Hi @oschina 

Did you solve this?

**Comment by oschina** [comment]
> Hi @oschina
> 
> Did you solve this?

we do this in another way ....
