### ISSUE TITLE
Cannot get isActive to match current route with queryparams

### ISSUE THREAD

**Issue by alkanna** [sveltech/svelte-filerouter#410]
Hello,

I have this route :
```
['./requests', { status: 'in_progress', type: 'pec' }, 'Relance Mut']
```
And I am trying to get isActive to be true if I am on said component, as well as with the right queryparams
`$isActive('./requests', { status: 'in_progress', type: 'pec' })` does not work as I thought it would, and instead returns false.

Is there something I missed ?

Thanks.

**Comment by jakobrosenberg** [comment]
Hi @alkanna , that should work. Can you provide a minimal reproducible of the issue?
