### ISSUE TITLE
SyntaxError: Unexpected token error on routing.

### ISSUE THREAD

**Issue by dewcked** [sveltech/svelte-filerouter#411]
#### With that out of the way, there are a few things that might help us help you faster. You pick and choose what you think is relevant.

**bug description**
Svelte files with possible filesystem names aren't handled in right way. Should I change settings or upgrade to routify 3.0?

**error in console**
`SyntaxError: Unexpected token (110:61) in ~~\.routify\routes.js`
`"component": () => import('../src/pages/posts/What's the svelte.svelte').then(m => m.default)`
                                                                                 ^ (error occurs in the quotes, also urlindex.json has double quotes.)

**version**
Routify 2.18.4, Svelte 3.0.0 only use rollup, without sapper, sveltekit and any other bundlers / unbundlers

**Comment by ghostdevv** [comment]
As a workaround I would suggest changing your filename for now, i can fix patch this later today for you

**Comment by dewcked** [comment]
Thank you for super fast reply. I think I found a good way to fix this.

special characters like whitespaces also incur same error. Encoding every special characters in filename to HTML style (like whitespace into %20) fixed all the problems.

**Comment by jakobrosenberg** [comment]
@dewcked I would strongly recommend using a slug format like: `only-numbers-latin-letters-and-dashes`.

https://yoast.com/slug/

**Comment by dewcked** [comment]
@jakobrosenberg I didn't knew that slugs affect SEO. Thanks for the info. 👍

**Comment by ghostdevv** [comment]
I was thinking about this and maybe we can warn in console if non url safe chars are used? @jakobrosenberg 

in terms of fixing the quote issue, either `String.raw` or `JSON.stringify` at a guess

**Comment by jakobrosenberg** [comment]
This is fairly low priority to me, but I'm open to a PR 🙂
