### ISSUE TITLE
Unable to naviagate to nested route (routify v3)

### ISSUE THREAD

**Issue by hyochan** [sveltech/svelte-filerouter#416]
**First rule of bug posting**
**There are no rules!**

#### With that out of the way, there are a few things that might help us help you faster. You pick and choose what you think is relevant.

**bug description**
It doesn't work as expected when navigating to `community/[id]` with `$goto`.
If you see the below recorded clip, when pressing `Feeds` button, it calls `$goto($url('/community/[id]/settings', {id: '1234'}))'` for testing but redirects to different url.

https://user-images.githubusercontent.com/27461460/146673420-ae2d3052-5f15-4b73-89d6-963d755636db.mp4

However, when I type the actual URL from the browser, it navigates correctly (in localhost but not in production).

https://user-images.githubusercontent.com/27461460/146673423-eeb98153-19a6-484e-87f4-732a63ea8274.mp4

**package.json**
The script section or even just the script you're running.

```
yarn dev
```

**version**
```
"@roxi/routify": "^3.0.0-next.69",
```

**screenshot**
I've posted clip above.

The source code is in https://github.com/wecount-dev/wecount

**Comment by hyochan** [comment]
By the way, why does the static URL not working in production? https://staging.wecount.dev/communities should work.

However, we need to navigate from [staging.wecount.dev](https://staging.wecount.dev) currently.

<img width="279" alt="Screen Shot 2021-12-20 at 1 07 00 AM" src="https://user-images.githubusercontent.com/27461460/146681904-1b4ac89e-8b86-48a4-a420-12123fbbcd7c.png">

By clicking the above button, you can navigate to the list. From here, you can try to click on `More` buttons to test the current issue problem.

<img width="178" alt="Screen Shot 2021-12-20 at 1 06 06 AM" src="https://user-images.githubusercontent.com/27461460/146681876-d4dd8e1e-5845-4122-a2a2-0be301756f56.png">

**Comment by hyochan** [comment]
FYI, when navigating from the `a` link, it works ok. However, using `$goto` will redirect with the above error.

**Comment by jakobrosenberg** [comment]
Hi @hyochan . Thanks for the feedback. I'll see if I can have a look tomorrow 🙂

**Comment by jakobrosenberg** [comment]
Can you confirm that changing this
```javascript
$goto($url('/community/[id]/settings', {id: '1234'}))'
```
to
```javascript
$goto('/community/[id]/settings', {id: '1234'})'
```
fixes it.

**Comment by hyochan** [comment]
> Can you confirm that changing this
> 
> ```js
> $goto($url('/community/[id]/settings', {id: '1234'}))'
> ```
> 
> to
> 
> ```js
> $goto('/community/[id]/settings', {id: '1234'})'
> ```
> 
> fixes it.

Confirm that this fixed the issue!! Strange tough 🤔

**Comment by hyochan** [comment]
@jakobrosenberg However, the issue still persists on the `static` URL.
https://staging.wecount.dev/communities is still not working.

**Comment by jakobrosenberg** [comment]
@hyochan could this be related to url rewrites?

On the dev server, all 404 requests are forwarded to the index.html. Once the browser has loaded the html and Routify, Routify then navigates to the address in the address bar.

On your production server I suspect that 404's are not forwarded, so Routify doesn't receive the requests unless the visitor goes directly to the index.html page (`/`).

**Comment by hyochan** [comment]
@jakobrosenberg Totally understood! Thanks for the response 🙏 

Really appreciate that.

**Comment by iCodePoet** [comment]
> Can you confirm that changing this
> 
> ```js
> $goto($url('/community/[id]/settings', {id: '1234'}))'
> ```
> 
> to
> 
> ```js
> $goto('/community/[id]/settings', {id: '1234'})'
> ```
> 
> fixes it.

@jakobrosenberg 

Does this apply when using only $goto?
The code below is accessible even with $url. Could you please explain this further?

```ts
location.href = $url('/community/[id]/setting', {
    id: '1234',
})
```

**Comment by hyochan** [comment]
> On your production server I suspect that 404's are not forwarded, so Routify doesn't receive the requests unless the visitor goes directly to the index.html page (`/`).

@jakobrosenberg I've been trying to resolve a current issue with [url rewrites](https://v3.ci.routify.dev/docs#guide/concepts/url-rewrites). However, I am not sure I am doing it right.

```
const urlRewrite = {
    toExternal: (url: string) => '/' + url,
    toInternal: (url: { replace: (arg0: number,arg1: string) => any; }) => url.replace(/^/, ''),
}

// and

<Router routes={routes} {urlRewrite} />

```

Looks like things are not resolving anything. Is there any guide for the SPA app?

**Comment by jakobrosenberg** [comment]
The URL rewrite has to happen on your server. Not inside Routify. The problem is Routify never receives the traffic from your server. How are you hosting in production?

**Comment by hyochan** [comment]
It is an spa app. I am hosting with github pages.

https://github.com/wecount-dev/wecount

I have recently migrated to routify v3 from svelte spa router

**Comment by jakobrosenberg** [comment]
Try copy index.html and rename it to 404.html

**Comment by hyochan** [comment]
@jakobrosenberg Tried but still wontfix :disappointed: 
https://github.com/wecount-dev/wecount/commit/9d2433327ccfe031e5a352999ecff6bfe9e4e66c

**Comment by jakobrosenberg** [comment]
You may have to enable hash based navigation then.

**Comment by Kiho** [comment]
I am not sure on this case but this usually works for me on github https://github.com/Kiho/smelte-crud-app/blob/master/docs/404.html
https://github.com/Kiho/smelte-crud-app/blob/master/docs/index.html

**Comment by hyochan** [comment]
> I am not sure on this case but this usually works for me on github https://github.com/Kiho/smelte-crud-app/blob/master/docs/404.html https://github.com/Kiho/smelte-crud-app/blob/master/docs/index.html

Tried here https://github.com/roxiness/routify/issues/416#issuecomment-1000987396, but won't work in my case.

**Comment by hyochan** [comment]
> You may have to enable hash based navigation then.

@jakobrosenberg 

```
<Router routes={routes} config={{useHash: true}} />
```

Thanks for the response. I've enabled hash routes in https://github.com/wecount-dev/wecount/commit/0aba7c116356de3769ff5e6924021de132fdae2b but now I see the below error.

<img width="908" alt="Screen Shot 2021-12-26 at 1 47 52 PM" src="https://user-images.githubusercontent.com/27461460/147399183-64d9138d-9eb3-47ba-b88b-0809684dfba9.png">

Anything else I can try further?

**Comment by jakobrosenberg** [comment]
Do you get the error in development? Looks like a vite error.

**Comment by hyochan** [comment]
> Do you get the error in development? Looks like a vite error.

No `dev` env works fine!

Below is vite config

```
import {defineConfig} from 'vite';
import preprocess from 'svelte-preprocess';
import routify from '@roxi/routify/vite-plugin';
import {svelte} from '@sveltejs/vite-plugin-svelte';

const production = process.env.NODE_ENV === 'production';

export default defineConfig({
  clearScreen: false,
  server: {port: 1337},
  plugins: [
    routify(),
    svelte({
      emitCss: true,
      compilerOptions: {dev: !production},
      extensions: ['.svelte'],
      preprocess: preprocess({
        postcss: true,
        sourceMap: !production,
      }),
      hot: !production,
    }),
  ],
});

```

**Comment by jakobrosenberg** [comment]
You might have to experiment a little with the Vite build config since it works in dev, but not build.

**Comment by hyochan** [comment]
@jakobrosenberg Looks like something corrupted in `github pages`. Previous working code seems to reproduce the same error currently. I'll try to figure it out and come back!

Thanks.

**Comment by hyochan** [comment]
I finally found out the problem. It was this commit https://github.com/wecount-dev/wecount/pull/123/commits/d33d1173f779a9194df9613b65afaebc775484df.

Removing `<!-- routify:meta bundle -->` finally worked and @jakobrosenberg your solution was correct.

Thank you so much!
