### ISSUE TITLE
Disabling the parent module does not work. (routify v3)

### ISSUE THREAD

**Issue by iCodePoet** [sveltech/svelte-filerouter#417]
# Disabling the parent module does not work.

**bug description**
https://v3.ci.routify.dev/docs#guide/introduction/modules
The parent module was disabled by annotating according to the document, but the parent module is still displayed.

**version**
"@roxi/routify": "^3.0.0-next.69"

**screenshot**
![image](https://user-images.githubusercontent.com/29420674/147139507-a767013f-3110-4a5d-a79e-8be60e5ae15e.png)
![Screenshot from 2021-12-23 03-31-56](https://user-images.githubusercontent.com/29420674/147139515-7d9e136a-d407-4715-82c0-e72b0b2d6e8c.png)

**Comment by jakobrosenberg** [comment]
Sorry about the late reply. I'll have a look at this.

**Comment by jakobrosenberg** [comment]
I'm not able to reproduce the issue on `3.0.0-next.76`. Could you try update your version and let me know if the issue persists?
