### ISSUE TITLE
Environment variables leak with -c command

### ISSUE THREAD

**Issue by bluwy** [sveltech/svelte-filerouter#429]
**bug description**

Routify uses configent. Configent by default has `useDotenv` true, which is non-configurable from Routify. When using the `routify -c other` command, where `other` will be executed in parallel while routify watches for routes, the `process.env.*` is leaked into `other` command's process.

I don't think this is expected, and the `other` command should be isolated.

I noticed this when configuring the `-c` command with a Vite dev server. The `.env` file loaded into `process.env.*`, causing the `.env` variables to have the highest precedence compared to `.env.production`, `.env.local` etc, which is unexpected. `.env.production` and `.env.local` should have higher precedence than `.env`.

**workaround**

For now I've followed the template using `run-p routify other`, which properly isolates the env var. 

**package.json**

```json
{
  "scripts": {
    "dev": "routify -c dev:vite",
    "dev:vite": "vite -m dev"
  },
  "dependencies": {
    "@roxi/routify": "^2.18.1"
  }
}
```

**version**

`@roxi/routify`: `2.18.3` from lockfile

~~(I checked the code and it seems to be the same for v3 too)~~

**Comment by ghostdevv** [comment]
Hey thanks for finding this @bluwy . We will see how we can patch this in R2, it shouldn't even be there in R3 as we don't wanna get involved with how users are running scripts if that makes sense? Especially as in R3 we ship a vite plugin

**Comment by bluwy** [comment]
Thanks for looking into this! Yeah looks like I checked the wrong branch for R3 😬

**Comment by ghostdevv** [comment]
I haven't been able to find a way to do this - I don't know much about child process, and blanking on examples of where I have seen a child process option before! If anyone has any ideas lmk

**Comment by bluwy** [comment]
Looks like [child_process.spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) has an option called `env` that defaults to `process.env`, which causes the issue. I don't think there's a safe way to exclude the env vars from `.env` though, or start with a fresh `process.env`. Perhaps the better solution is to have `configent` to use `dotenv` without polluting `process.env`, by reading the parsed key-value pairs only.
