### ISSUE TITLE
webpack errors while bundling runtime lib

### ISSUE THREAD

**Issue by vkunz** [sveltech/svelte-filerouter#437]
hi,

I pulled routify into a project with webpack as bundler.

While building, webpack yelled at me with the following error:

<details>
  <summary>Error</summary>
  
  <pre>
    ERROR in ./node_modules/@roxi/routify/lib/runtime/Route/RouteFragment.js 1:0-42
    Module not found: Error: Can't resolve './utils' in '<project-dir>/node_modules/@roxi/routify/lib/runtime/Route'
    Did you mean 'utils.js'?
    BREAKING CHANGE: The request './utils' failed to resolve only because it was resolved as fully specified
    (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
    The extension in the request is mandatory for it to be fully specified.
    Add the extension to the request.
    resolve './utils' in '<project-dir>/node_modules/@roxi/routify/lib/runtime/Route'
    using description file: <project-dir>/node_modules/@roxi/routify/package.json (relative path: ./lib/runtime/Route)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: <project-dir>/node_modules/@roxi/routify/package.json (relative path: ./lib/runtime/Route/utils)
        Field 'browser' doesn't contain a valid alias configuration
        <project-dir>/node_modules/@roxi/routify/lib/runtime/Route/utils doesn't exist
    @ ./node_modules/@roxi/routify/lib/runtime/Route/Route.js 1:0-51 189:27-40 200:32-45 236:34-47 246:44-57
    @ ./node_modules/@roxi/routify/lib/runtime/Router/Router.js 24:0-42 322:22-27
    @ ./node_modules/@roxi/routify/lib/runtime/index.js 3:0-73 11:0-132 11:0-132
    @ ./src/frontend/src/App.svelte 16:0-39 24:14-20 86:34-40
    @ ./src/frontend/src/app.ts 1:0-31 2:16-19

    webpack 5.70.0 compiled with 1 error and 1 warning in 3756 ms
  </pre>
</details>

Adding the '.js' extension to the import avoids this error, and
results in a successful build.

This is such a tiny change, it does not really warrant a pr.

<details>
  <summary>Patch</summary>
  
```patch
diff --git a/lib/runtime/Route/RouteFragment.js b/lib/runtime/Route/RouteFragment.js
index 1685563..b560baf 100644
--- a/lib/runtime/Route/RouteFragment.js
+++ b/lib/runtime/Route/RouteFragment.js
@@ -1,4 +1,4 @@
-import { URIDecodeObject } from './utils'
+import { URIDecodeObject } from './utils.js'

export class RouteFragment {
    /**
```
</details>

BR,
vkunz

<details>
  <summary>Versions</summary>

  - node: v16.14.2
  - @roxi/routify: 3.0.0-next.83
  - svelte: 3.46.4
  - svelte-loader: 3.1.2
  - svelte-preprocess: 4.10.4
  - typescript: 4.6.2
  - webpack: 5.70.0

</details>

**Comment by ghostdevv** [comment]
Sorted
