### ISSUE TITLE
`vite-plugin-svelte` raises a warning in console

### ISSUE THREAD

**Issue by jerrygreen** [sveltech/svelte-filerouter#439]
Warning (Error?):

> node_modules/@roxi/routify/lib/runtime/Instance/Node.svelte:16:8 <Component/> will not be reactive if Component changes. Use <svelte:component this={Component}/> if you want this reactivity.

Versions:

> "@roxi/routify": "3.0.0-next.83",
> "@sveltejs/vite-plugin-svelte": "1.0.0-next.40",
> "vite": "2.8.4",
> "svelte": "3.46.4",

**Comment by ghostdevv** [comment]
You can ignore this, its becuase internally routify uses svelte:component but doesn't bind it, this is intentional

The warning is annoying, I asked around and we can't suppress it so we make migrate to binding in the future as long as there's no measurable performance hit
