### ISSUE TITLE
E404 when having E-Mail Adress in URL 

### ISSUE THREAD

**Issue by Kapsonfire** [sveltech/svelte-filerouter#440]
If you directly access (like refreshing page) on DEV mode, you'll get a 404 Error, when the url contains a correct e-mail address.
Encoding the @ to %40 doesnt work as well

http://localhost:5000/Users/Anariba%40le.com <<< error 404
http://localhost:5000/Users/Anariba%40 <<< works

```javascript
"devDependencies": {
        "@fullhuman/postcss-purgecss": "^4.1.3",
        "@roxi/routify": "^2.18.5",
        "@sveltejs/vite-plugin-svelte": "^1.0.0-next.34",
        "autoprefixer": "^10.4.2",
        "npm-run-all": "^4.1.5",
        "postcss": "^8.4.5",
        "postcss-import": "^14.0.2",
        "svelte": "^3.45.0",
        "svelte-preprocess": "^4.10.1",
        "tailwindcss": "^3.0.23",
        "vite": "^2.7.10"
    },
```

**Comment by jakobrosenberg** [comment]
Hi @Kapsonfire-DE, are you using R2 or R3?

**Comment by Kapsonfire** [comment]
See at devDependencies
"@roxi/routify": "^2.18.5",

**Comment by Kapsonfire** [comment]
btw Folder structure
```
pages/Users/[username].svelte

**Comment by Kapsonfire** [comment]
Happens in V3 as well.

**Comment by Kapsonfire** [comment]
![image](https://user-images.githubusercontent.com/67053124/160246292-040029e1-ffd9-40fa-b6f4-10aa43c88d23.png)

![image](https://user-images.githubusercontent.com/67053124/160246296-c62d1036-b252-4d7a-8781-9833d5326504.png)

**Comment by ghostdevv** [comment]
It's the `.` in the url - unsure as to why at the moment

**Comment by Kapsonfire** [comment]
I disagree. Its not the dot in the url

happens with: 
```http://localhost:5000/Users/username@domainwithoutdot```

as well...

**Comment by ghostdevv** [comment]
I think this might be something to do with vite, which I assume you are using? I made this reproduction here: https://github.com/ghostdevv/routify-email-repro 

if you run this repro locally when you press the `hey@dom.com` link it will work but when you refresh it breaks, this tells me it's not a routify bug but something with vite, so will look into that

Another thing that confirms that is this online version on netlify works <https://iridescent-figolla-93b887.netlify.app/>

**Comment by Kapsonfire** [comment]
Yeah vite is used. So i guess im gonna test this issue with vite without routify.

**Comment by Kapsonfire** [comment]
Using with vite and a vanilla project works fine
```
kapsonfire@KAPS-PC:/mnt/c/projects$ npm create vite@latest testvite
Need to install the following packages:
  create-vite@latest
Ok to proceed? (y)
✔ Select a framework: › vanilla
✔ Select a variant: › vanilla

Scaffolding project in /mnt/c/projects/testvite...

Done. Now run:

  cd testvite
  npm install
  npm run dev


kapsonfire@KAPS-PC:/mnt/c/projects$ cd testvite

kapsonfire@KAPS-PC:/mnt/c/projects/testvite$ npm install

added 14 packages, and audited 15 packages in 2s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
kapsonfire@KAPS-PC:/mnt/c/projects/testvite$ npm run dev
````

**Comment by ghostdevv** [comment]
Using vanilla vite doesn't work

**Comment by ghostdevv** [comment]
Upon doing some digging vite deliberately doesn't rewrite urls with a `.` character in them, I haven't found why yet but I have found this plugin that you can use <https://github.com/ivesia/vite-plugin-rewrite-all>

**Comment by ghostdevv** [comment]
Ok so the reason it doesn't work, and I can't believe I missed this, is because it was in the last segment of the url. So a path like `/hey@dot.com/test` would work as the `.com` segment is not the last segment of the url. I believe vite doesn't rewrite this as it assumes you might be attempting to access a file or something like that, at any rate the plugin should solve your issue

**Comment by Kapsonfire** [comment]
Works - thanks
