### ISSUE TITLE
Visual Glitch

### ISSUE THREAD

**Issue by osmancoskun** [sveltech/svelte-filerouter#448]
**bug description**
everything works as expected in `_layout.svelte` but a small problem when entering url from browser. 
whenever i try to   browse any pages from browser, it doesnt let me. 
because i have `userLoggedIn` in store and i check it in `_layout.svelte`.
but when i hit the url like `http://localhost:5000/`
it shows a bit of my homepage then suddenly redirect to login page. but a bit  of page has been exposed. just a visual thing.
## `_layout` code
```
{#if !$userLoggedIn}
  <slot />
  {$goto("./login")}
{:else}
  <Header />
  <div
    class="ui bottom  attached segment pushable"
    style="background-color:lightgray;"
  >
    <Sidebar />
    <MainContent>
      <slot />
    </MainContent>
  </div>
{/if}
```
**package.json**
```
{
  "name": "routify-starter",
  "private": true,
  "scripts": {
    "dev": "run-p dev:*",
    "dev:routify": "routify",
    "dev:vite": "vite",
    "preview": "vite preview",
    "build": "run-s build:*",
    "build:routify": "routify -b",
    "build:vite": "vite build"
  },
  "devDependencies": {
    "@roxi/routify": "^2.18.4",
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.34",
    "autoprefixer": "^10.4.2",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.5",
    "postcss-import": "^14.0.2",
    "svelte": "^3.45.0",
    "svelte-preprocess": "^4.10.1",
    "vite": "^2.7.10"
  },
  "dependencies": {
    "buffer": "^6.0.3",
    "moment": "^2.29.1",
    "socket.io": "^4.4.1",
    "socket.io-client": "^4.4.1",
    "svelecte": "^3.6.0",
    "svelte-select": "^4.4.7"
  }
}
```
**version**
svelte:3.45.0
routify:2.18.4

**screenshot**
![Peek 2022-04-09 00-53](https://user-images.githubusercontent.com/44034936/162537052-2f4081d8-ebea-4181-8877-85d5632f265d.gif)

**Comment by osmancoskun** [comment]
also when using `{$goto("./login")}` it shows in page like `undefined` so i have to use it with `<slot/>` but it expands my page size. also if i dont use slot i cant get my login page.
![Screenshot from 2022-04-09 01-05-01](https://user-images.githubusercontent.com/44034936/162538755-29b0c233-72e1-49c9-84e4-7ef116cd2fd2.png)

**Comment by jakobrosenberg** [comment]
`undefined` usually means you're calling a function in your template with no return value. I can't tell its origin from what you posted.

**Comment by osmancoskun** [comment]
> 

it comes from `{$goto("./login")}`. when i remove it. there is no problem.

**Comment by ghostdevv** [comment]
don't use goto in your markup, use it in your script tag

**Comment by osmancoskun** [comment]
so should i use `$:` for listening store variable for redirecting user if not logged in? or do you suggest something better?

**Comment by ghostdevv** [comment]
Yea that would be better

**Comment by osmancoskun** [comment]
thanks for everything.

**Comment by ghostdevv** [comment]
Np
