### ISSUE TITLE
--host flag not working

### ISSUE THREAD

**Issue by dustsucker** [sveltech/svelte-filerouter#449]
**bug description**
-- Host is not working

**package.json**
{
  "name": "routify-starter",
  "private": true,
  "scripts": {
    "dev": "run-p dev:*", // or "run-p dev:* --host" both do not work
    "dev:routify": "routify",
    "dev:vite": "vite",
    "preview": "vite preview",
    "build": "run-s build:*",
    "build:routify": "routify -b",
    "build:vite": "vite build"
  },
  "devDependencies": {
    "@roxi/routify": "^2.18.3",
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.5",
    "autoprefixer": "^10.2.5",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.2.8",
    "postcss-import": "^14.0.0",
    "svelte": "^3.35.0",
    "svelte-preprocess": "^4.7.0",
    "svelte-typewriter": "^3.0.0-alpha.11",
    "tailwindcss": "^3.0.23",
    "vite": "^2.0.5",
    "prettier": "^2.6.1",
    "prettier-plugin-tailwindcss": "^0.1.8"
  },
  "dependencies": {
    "@rollup/plugin-json": "^4.1.0",
    "carbon-icons-svelte": "^10.44.4",
    "daisyui": "^2.13.4",
    "svelte-i18n": "^3.3.12",
    "svelte-magnifier": "^0.0.1",
    "zxcvbn": "^4.4.2"
  }
}

i tryied using it in the comand so npm run dev --host died not work then i tried it in the package.json with run-p dev:* --host and it returns: 
npm run dev --host

> dev
> run-p dev:* --host

ERROR: Invalid Option: --host

is there another thing i could try so it works?

**Comment by ghostdevv** [comment]
You need to add it to the vite script:

```json
"dev:vite": "vite --host",
```
