### ISSUE TITLE
How to integrate Ionic lifecycle hooks

### ISSUE THREAD

**Issue by Tommertom** [sveltech/svelte-filerouter#454]
Hi there

Just finished big chunk of the working integrating Ionic 6 ui lib with vite and your great router

https://github.com/Tommertom/svelte-ionic-app

Now the biggest challenge is implementing the page lifecycle hooks for devs to easily use

There are four - view did/will enter and view did/will leave (see 
https://ionicframework.com/docs/angular/lifecycle)

Now I wonder what suggestions you may have implementing these using your v2 router.

And biggest question contained therein to me seems:can I use the existing goodies of the router or will it require changes to e.g. Route or Router svelte components?

Thx for the continued work on this project!

**Comment by jakobrosenberg** [comment]
Hi Tommertom. There are a lot of ways to do this, but I'm not sure which would suit you best as I have very little experience with Ionic.

As for lifecycle hooks. I think `$beforeUrlChange` is what you're looking for. Combined with `$page` you should be able to grab the incoming and outgoing page before and after transitions.

Decorators could be a great way to solve this.
[Example of transitions using decorators](https://example.routify.dev/example/transitions/tabs/home)
[source](https://github.com/roxiness/routify-starter/blob/master/src/pages/example/transitions/tabs/_reset.svelte)


Feel free to follow up as I'm sure we can narrow down a more concrete solution for you.

Also, would you be interested in upgrading to V3?

**Comment by Tommertom** [comment]
Hey there and thanks for the reply

Let me look these up and possibly do some code examples

As to v3 - I am a bit in the blind. You are better positioned to make statements on the status of v3 going into full live vs your current userbase on v2

**Comment by Tommertom** [comment]
So just to let you know my design objective:


SomePageComponent.svelte snippet:

```
<script lang="ts">
import {IonPage> from '@ionic/svelte' // does not exist yet - this is the big todo

const willEnterFn=didEnterFn=didEnterFn=willLeaveFn = ()=>{console.log('PAGE EVENT TIGGER');

// willEnter - page will enter into view = page is selected to become next in view (so directly after route change)
// didEnter - page has entered into view = page shown, ideally also after completion of any css animation
// willLeave- triggered when route change is triggered (equal to next-page's willEnter)
// didLeave - triggered when page left out of view, ideally also after completion of any css animation

</script>

<IonPage on:ionViewWillEnter={willEnterFn} on:ionViewDidEnter={didEnterFn}  on:ionViewWillLeave={willLeaveFn} on:ionViewDidLeave={didLeaveFn} >

... whatever svelte html magic goes here

</IonPage>
```
Here the hooks are bound using event handling. But it can also be implemented using properties, if that works better (for instance when communicating via a store)

**Comment by Tommertom** [comment]
Hi

Hope you don't mind me posting here some progress and things I am trying out.

So, I did not yet go for the hooks you mentioned (beforeUrl change and page).  I did do a lot of console.logging with them to figure out when they fire, but I could not fully grasp it. Also because I need to be able to dispatch events towards two different components in the same route change event. That did not go well together because of an issue mentioned below (component being able to identify its own route).

So now what I did:
* I create a store that emits the events to whatever component wants to consume.
* In the Route.svelte of your lib I emitted the events in the place where I thought it was most appropriate to do so (in the setComponent function)
* The IonPage component (which wraps the pages) listens in for the events and compares it to its own route (provided for using a property)
* The IonPage consumes the events through properties, not event handlers. Within IonPage it subscribes to the store.

There might be some issues with this way, but the challenge I faced was identifying the component's own route using $url(). This did not seem to give different values for the different components when transitioning. And there are no functions in svelte itself allowing me to identify the component and compare with route.

A bit more explanation - https://ionicsvelte.firebaseapp.com/components/Page

So now I am left with a few questions:
- can dispatch be used instead of store?
- are there better places to emit the events?
- how to be smarter about component-route identification (or get rid of it at all)

Thx for your time :)

**Comment by jakobrosenberg** [comment]
No problem. Love to get some insight in how Routify is used.

At this point I would strongly consider moving to R3 as R3 is made for the kind of integration you're doing. From a maintenance POV I think you'll save a lot of time and I'll be happy to help where I can.

**Comment by Tommertom** [comment]
> No problem. Love to get some insight in how Routify is used.
> 
> At this point I would strongly consider moving to R3 as R3 is made for the kind of integration you're doing. From a maintenance POV I think you'll save a lot of time and I'll be happy to help where I can.

Upgrade guide in the docs - even very brief would be nice.... Or maybe even simpler - adding to existing project? Happy to remove v2 and then add v3......

Or is it like https://www.routify.dev/guide/installation/install-to-existing-project but then with @next?

I did npm i ...@next and then npm complains about routify not being present... So a bit of guidance would be appreciated.  :)

**Comment by jakobrosenberg** [comment]
Heh, yes. There's no upgrade guide yet. V3 is so different we even contemplated using a different name. Do you have a branch I can try out for a migration?

**Comment by Tommertom** [comment]
> Heh, yes. There's no upgrade guide yet. V3 is so different we even contemplated using a different name. Do you have a branch I can try out for a migration?

https://github.com/Tommertom/svelte-ionic-app/tree/roxy3

**Comment by jakobrosenberg** [comment]
Created a PR for Routify 3 here.
https://github.com/Tommertom/svelte-ionic-app/pull/28/commits

**Comment by Tommertom** [comment]
Hi @jakobrosenberg 

I am getting this message on branch master of my project, npm run dev:

`10:05:30 PM [vite-plugin-svelte] C:/Data/src/svelte-ionic-app/node_modules/@roxi/routify/lib/runtime/Instance/Node.svelte:16:8 <Component/> will not be reactive if Component changes. Use <svelte:component this={Component}/> if you want this reactivity.
`

Any suggestions - does not seem a big problem for now. Not breaking the build

**Comment by jakobrosenberg** [comment]
The warning is a quirk of Svelte that we haven't solved yet. Svelte wants the component to be dynamic so that it'll update if changed. The problem is that it's not dynamic and making it so will multiply its size, so we're stuck between a large component and no warnings or a small component with pointless warnings.

@ghostdevv any idea if there's a way to solve it?

**Comment by ghostdevv** [comment]
Have you tried just doing `<Component />` in the code? @jakobrosenberg

**Comment by jakobrosenberg** [comment]
@ghostdevv https://github.com/roxiness/routify/blob/76d90f9ee4aee332bb4406466e593ba4096b4fb0/lib/runtime/Instance/Node.svelte#L16-L18

**Comment by Tommertom** [comment]
Resolved
