### ISSUE TITLE
Why are these types not exported?

### ISSUE THREAD

**Issue by petermakeswebsites** [sveltech/svelte-filerouter#465]
[routify](https://github.com/roxiness/routify)/[typings](https://github.com/roxiness/routify/tree/master/typings)/typedef.d.ts

Is there any reason why these are not exported? Trying to get types for the complex transition objects, figured I would build my own from the parts, but then realized these are not even exported. Am I missing something?

**Comment by jakobrosenberg** [comment]
That's an error on our part I think. Interested in doing a PR?

**Comment by petermakeswebsites** [comment]
I'm happy to write it by hand, but are these generated from JSDoc using TS type compiler? In which case, would I be setting types in JSDoc and then running the TS type compiler? If the ladder, I _may_ be slightly out of my depth.

**Comment by jakobrosenberg** [comment]
Yes, the types are generated from JSDoc, but you can also use `.d.ts` files. In fact I've started slowly moving to `.d.ts` files for R3.

I think the missing export is just a matter of editing `package.json` but I might be missing something.

**Comment by hobbitronics** [comment]
is all that is needed in the package.json just `"types": "./routify/typings/typedef.d.ts"`? It seems to be able to find the types when I ctrl + click so maybe this is not longer an issue.

**Comment by jakobrosenberg** [comment]
@hobbitronics could you expand on that? I don't fully follow. 🙂

**Comment by hobbitronics** [comment]
> @hobbitronics could you expand on that? I don't fully follow. 🙂

Sure. When I was using the type `ClientNodeApi` in a callback parameter for `beforeUrlChange`, I was able to ctrl + click on it in my code. My ide it took me to typedef.d.ts. Doesn't that mean it is being exported if my ide knows about it without me explicitly importing it? I'm not exactly where its getting it from but seems to work in my case already.

**Comment by jakobrosenberg** [comment]
Yes. It sounds like it's working as it's supposed to. I'll close this issue as it has gotten stale. Thanks for the update!
