### ISSUE TITLE
"Couldn't find context" when using $url params (~v3.0.0-next.94)

### ISSUE THREAD

**Issue by andy1li** [sveltech/svelte-filerouter#470]
**bug description**
`$url (path, params)` doesn't work anymore.

**minimal repo**
https://github.com/andy1li/routify-bug-report

**reproduction steps**
1. Click "Goto Inner Page"
2. Error

**version**
Routify: ~v3.0.0-next.94
(It worked fine up until .93)

**screenshot**
![](https://github.com/andy1li/routify-bug-report/raw/main/context-error.png)

**Comment by jakobrosenberg** [comment]
Thanks for reporting this @andy1li . Will have a fix out ASAP.

**Comment by jakobrosenberg** [comment]
Thanks again for the feedback on this. Please let me know if this fixes the issue on your end. 🙂

**Comment by andy1li** [comment]
Works like a charm! 👍👍👍 

Thank you @jakobrosenberg for your time and the wonderful package! 🎁

---

Something else really quick:

v3 has been generating some warning like `@roxi/routify/lib/runtime/Instance/Node.svelte:17:8 <Component/> will not be reactive if Component changes. Use <svelte:component this={Component}/> if you want this reactivity` (which I have been suppressing in vite.config).

But recently there's another warning popping up `@roxi/routify/lib/runtime/decorators/ScrollDecorator.svelte:89:15 ScrollDecorator has unused export property 'Parent'. If it is for external reference only, please consider using "export const Parent"`.

Should I open another issue so that they're easier to track?

**Comment by jakobrosenberg** [comment]
Yes, please. The warnings have been a real painpoint. Creating an issue for them might foster some good ideas.
