### ISSUE TITLE
Please expose a navigation store with from and to routes

### ISSUE THREAD

**Issue by kristianmandrup** [sveltech/svelte-filerouter#477]
**Is your feature request related to a problem? Please describe.**

When doing Page transitions, it is necessary to have the `from` page and `to` page as in this demo:

https://www.youtube.com/watch?v=ua6gE2zPulw

Demo is based on the new Page Transition API (currently Chrome canary). We are working on trying to add support for Ionic mobile like page transitions with Svelte, using routify: https://github.com/Tommertom/svelte-ionic-app/issues/32

**Describe the solution you'd like**

Expose a `navigation` store with an object containing `from` and `to` each a `RouteDestination`. 

```ts
type RouteDestination = {
  url: string
  data?: Record<string, any>
}

type NavigationStore = {
  from?: RouteDestination
  to?: RouteDestination
  state?: 'started' | 'loading' | 'complete' 
}
// create store
const navigation = writable({})

// update store when loading route
const to = {url, data}
navigation.update(nav => ({from: nav.to, to, state: 'started' })

// when done
navigation.update(nav => {...nav, state: 'completed' }
```

Could `goto` perhaps take an optional url `alias` or simply `data` to make it more convenient to match on specific routing transition pairs

```js
// pass url fragment and optional data object
goto('/products/1', {alias: 'product', id: 1})
```

In the router/route engine set this navigation store accordingly. Then we can subscribe to this store from any component. Would perhaps also be good with additional life cycle methods (pending?) as demonstrated in the video.

For the ultimate flexibility, allow passing in a custom create `Route` factory method to the router

```js
export createRoute = (opts = {) => new MyRoute(opts)

class MyRoute extends Route {
  // ..
}
```

```svelte
<script>
import { createRoute } from './my-route` 
</script>

<Route createRoute={createRoute} />
```

**Describe alternatives you've considered**

**Additional context**

**Comment by jakobrosenberg** [comment]
Hi @kristianmandrup 

I assume you're using Routify 3.

I like the idea of exposing load states of pending routes. We currently have `$activeRoute` and `$pendingRoute` that lets you create your own store. 

```javascript
$: store = {
  from: $activeRoute
  to: $pendingRoute 
  state: $pendingRoute ? 'started'  :  'complete' 
}
```

That should do the trick, though you would only have one state for "started" and "loading".

> Could goto perhaps take an optional url alias or simply data to make it more convenient to match on specific routing transition pairs

I'm not sure I fully understand this

> For the ultimate flexibility, allow passing in a custom create Route factory method to the router

It's possible to create routes in realtime, but I'm not sure if it has been documented yet.

**Comment by kristianmandrup** [comment]
Thanks a lot @jakobrosenberg. Yes, using routify 3. Your proposal should fit the bill in terms of integration points. Cheers!
Looking forward to improved docs for routify 3 as it gets closer to release :)

**Comment by jakobrosenberg** [comment]
That's great. I'll close this then. 😊

**Comment by kristianmandrup** [comment]
Cool :) I'm working on Svelte and Routify 3 integration in this repo https://github.com/kristianmandrup/svelte-routify3-page-transition-app using the example by @geoffrich
