### ISSUE TITLE
Handling /index paths

### ISSUE THREAD

**Issue by cooperwalbrun** [sveltech/svelte-filerouter#494]
I am new to Routify (and I am liking it a lot so far!), but there is one thing I am trying to do that I have not been able to find information about online: customize the way `/index` paths are handled. Specifically, what I am after is a way to redirect all `/index` paths to the corresponding `/`. For example, if this is my file structure:

```
/pages
  /something
    index.svelte
  index.svelte
```

I would have

* `/`
* `/index`
* `/something`
* `/something/index`

available at runtime. However, I would like to implement redirects (ideally using something like `$redirect` so the browser history is not polluted) from `/index` to `/` and `/something/index` to `/something` respectively. Is there a pattern for this? Or, is it not possible using the current Routify API? I know this use case can be handled at the server level, but I was hoping there might be a way to do it directly in the application code instead.

For reference, I am using `v2.18.8` of `@roxi/routify`. I apologize in advance if this is a common/simple use case to solve and my internet search skills have failed me.

**Comment by cooperwalbrun** [comment]
I should also mention that, at least for my use case, an alternative could be to simply disable the `/index` routes altogether so that my `_fallback.svelte` can catch the resulting 404s and redirect the user back to e.g. the homepage. I prefer the redirect approach described above, but if that is not possible, is there at least a way to "toggle" the `/index` routing?

**Comment by jakobrosenberg** [comment]
Hi, you should be able to redirect with the redirect option. TBH, I'm not sure if this is documented.

Plain
```
<!-- routify:options redirect="/some/path" -->
```

With parameters
```
<!-- routify:options redirect={"path": "/some/path", "params": {"id": "1"} -->
```

**Comment by cooperwalbrun** [comment]
>Hi, you should be able to redirect with the redirect option.

How would this look in practice? I tried adding

```html
<!-- routify:options redirect="/" -->
```

To the top of my `pages/index.svelte`, and I kept getting errors like this:

```
/index is redirecting to non-existent path: /
```

When I tried using this:

```html
<!-- routify:options redirect="/index" -->
```

I got the same error:

```
/index is redirecting to non-existent path: /index
```

**Comment by jakobrosenberg** [comment]
Could you try this
```
<!-- routify:options redirect="" -->
```

Routify looks for a route with the given path minus `/index`.

**Comment by cooperwalbrun** [comment]
Using
```html
<!-- routify:options redirect="" -->
```
does not produce any errors, but it does not prevent me from navigating to `/index` (i.e. it does not redirect from `/index` back to `/`).

**Comment by jakobrosenberg** [comment]
My mistake. I had misread your original post.

`/path` and `/path/index` are the same paths, so you wouldn't be redirecting. At least not internally.

I think `urlTransform` might be what you're looking for.
https://www.routify.dev/docs/config/runtime

If that doesn't work, you can also use `history.replaceStateNative` combined with `$afterPageLoad`.

```javascript
// in your root _layout.svelte
import { afterPageLoad }  from '@roxi/routify'

$afterPageLoad(page => {
  const newUrl = location.href.replace(/\/index$/, '')
  history.replaceStateNative(null, null, newUrl)
}) 
```

**Comment by cooperwalbrun** [comment]
The `$afterPageLoad` method works! I tried doing this first:

```typescript
const config = {
  urlTransform: {
    apply: url =>  url.endsWith('/index') ? url.substring(0, url.lastIndexOf('/index')) : url,
    remove: url => url,
  }
};
```

But that did not change the URL when I navigated to `/index`. Maybe my understanding of this approach is wrong?

Anyway, your code snippet using `$afterPageLoad` works like a charm, so that is what I will use. I really appreciate your help with this!

As a matter of personal curiosity before I close this issue, is there any way to disable this `/index` routing behavior altogether?

**Comment by jakobrosenberg** [comment]
You could do `./something.svelte` instead of `./something/index.svelte`, but I would advice against it. I find mixing library routing and file routing confusing.

Technically you are navigating to `something/index` so I think keeping the solution in the presentation layer (replaceState) makes it easier to reason about the internals.
