### ISSUE TITLE
$params broken (search params missing) after ~v3.0.0-next.174

### ISSUE THREAD

**Issue by andy1li** [sveltech/svelte-filerouter#524]
### Describe the bugs

1. `$params` won't pick up search params any more.

2. Unnecessary `index` appears in url. For example: 

`localhost:1337?foo=bar` redirects to `localhost:1337/index?foo=bar`

**screenshot 1:**

![image](https://github.com/roxiness/routify/assets/1450947/27920455-807e-4821-aed9-978b53d33417)

**screenshot 2:**

![image](https://github.com/roxiness/routify/assets/1450947/384d082c-fd31-42f5-bf03-b6789d592358)

### Reproduction

**minimal repo:**

https://github.com/andy1li/routify-bug-report

### System Info

```shell
System:
    OS: macOS 11.7.9
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
    Memory: 481.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  npmPackages:
    @roxi/routify: next => 3.0.0-next.176
    svelte: latest => 4.2.0
    vite: latest => 4.4.9
```

**Comment by jakobrosenberg** [comment]
Thanks for the repro @andy1li . I'll get back to you asap.

**Comment by andy1li** [comment]
Wow, thank you @jakobrosenberg for the lightning fast fix!

BTW, search params seem to add an unnecessary `index` in url. For example:

`localhost:1337?foo=bar` redirects to `localhost:1337/index?foo=bar`

Not sure whether this is an intended behavior.

**Comment by jakobrosenberg** [comment]
@andy1li thanks for the heads up. That's unintended, but harmless. I'll see if I can fix it.

**Comment by jakobrosenberg** [comment]
This should be fixed now.
