### ISSUE TITLE
Compatibility with Vite 5

### ISSUE THREAD

**Issue by michaelnero** [sveltech/svelte-filerouter#536]
### Describe the feature

Vite 5 has been released, but the package definition has a peer dependency of Vite "^3.2.4 || ^4.0.0". I wanted to create a pull request to fix this, but I could get the test suite to run out of the box, so I can't make changes and verify my changes unfortunately.

**Comment by ghost** [comment]
@jakobrosenberg Ain't the case anymore because Vite 5.0 is listed: https://github.com/roxiness/routify/blob/next/package.json#L112

**Comment by jakobrosenberg** [comment]
Thanks @james-em and @michaelnero . I'll close this.
