### ISSUE TITLE
v3:  derived helpers became broken after svelte migration from 3.x to 4.x

### ISSUE THREAD

**Issue by MarvinMiles** [sveltech/svelte-filerouter#539]
### Describe the bug

After Svelte migration from version 3.x to 4.x, using helpers such as `$url()` or `$goto` started causing an error during page rendering: `derived() expects stores as input, got a falsy value`

![Screenshot 2023-12-19 142702](https://github.com/roxiness/routify/assets/1912057/2e0bc506-c906-4c77-877b-ac81658ed5f0)

### Reproduction

Repro link: https://stackblitz.com/edit/vitejs-vite-2oa73k?file=src%2FApp.svelte,src%2FWrapper.svelte
Just uncomment `// $goto("/")`  and check devtool console

### System Info

```shell
-
```

**Comment by jakobrosenberg** [comment]
Thanks for the report. This is to be expected since the helpers need to exist within the scope of a router to access its context.

We should probably log this warning as an actual console.warning.

![image](https://github.com/roxiness/routify/assets/4153004/8de47952-b6c9-4222-9da8-fd48706b16ce)

Closing this, but feel free to follow up if you have questions or suggestions. 🙂

**Comment by MarvinMiles** [comment]
@jakobrosenberg Hey, thanks for fast response.

I can't really get it. Does this mean that helpers should be used inside `routes` folder? Like is this example: https://github.com/roxiness/routify/blob/266ec2359ad726f8006f24eb64affe056091e13b/examples/express/client/routes/examples/%5Bmode%5D/auth-example/admin/signin/index.svelte#L12

Thanks.

**Comment by jakobrosenberg** [comment]
@MarvinMiles, apologies if I wasn't clear. It has to be inside a file that's directly or indirectly imported by Routify. The physical location of the file doesn't matter.

For instance, all pages, modules and decorators are imported by Routify. Any files you import from a page, module or decorator is indirectly imported by Routify.

Example:
Routify imports `routes/_module.svelte`
Inside `routes/_module.svelte` you manually import `../components/MyWidget.svelte`

In this example, `MyWidget.svelte` is indirectly imported by Routify. `main.js` -> `App.svelte` -> `<Router/>` -> `_module.svelte` -> `MyWidget.svelte`. Meanwhile `<Router />` is a child of `main.js` -> `App.svelte` meaning that these two files live outside the context of Routify.
