### ISSUE TITLE
v3: Setting meta `title` value cause console warning

### ISSUE THREAD

**Issue by MarvinMiles** [sveltech/svelte-filerouter#542]
### Describe the bug

Setting inline `title` meta key for customizing route title cause console warnings for each route that uses `title` key.
```
[Routify 3][warn] Unrecognized meta keys detected:
  - "title" found in "docs/md/backend/index.md"
 ```
Yet `title` key works as expected. 

So not sure if this is an actually a bug. Nevertheless, this looks counter intuitive because I use this key intentionally, as described in documentation.

### Reproduction

-

### Logs

```shell
[Routify 3][warn] Unrecognized meta keys detected:
  - "title" found in "docs/md/backend/index.md"
//... etc.
```

### System Info

```shell
3.0.0-next.209
```

**Comment by jakobrosenberg** [comment]
Thanks for catching this @MarvinMiles . Should be fixed now.
