### ISSUE TITLE
[Bug][Doc][v3] Invalid Url Rewrites example

### ISSUE THREAD

**Issue by ghost** [sveltech/svelte-filerouter#545]
### Describe the bug

https://routify.dev/docs/guide/concepts/url-rewrites

1. urlRewrite needs to be passed to the createRouter({...}) method
2. The regex needs to escape the / to be valid javascript

Corrected example

```javascript
<script>
    import { Router, createRouter } from '@roxi/routify'
    import routes from '../.routify/routes.default.js'

    /** @type {UrlRewrite}*/
    const urlRewrite = {
        toExternal: url => '/my-app' + url,
        toInternal: url => url.replace(/^\/my-app/, ''),
    }

    export const router = createRouter({ routes, urlRewrite })
</script>

<Router {router} />
```

### Reproduction

Use the demo example for v3

### System Info

```shell
v3.0.0-next.216
```

**Comment by jakobrosenberg** [comment]
Thank you @james-em 😊

**Comment by ghost** [comment]
@jakobrosenberg 

You only fixed #2 though, the code is still invalid

**Comment by jakobrosenberg** [comment]
Ah, right. I was a bit hasty.

**Comment by jakobrosenberg** [comment]
This should be fixed now.
