### ISSUE TITLE
[Bug][V3] Routify renders 404 a fraction of second when using URLRewrite

### ISSUE THREAD

**Issue by ghost** [sveltech/svelte-filerouter#546]
### Describe the bug

Let's say my Svelte app has an homepage with the following URL http://localhost:3000/app/home and have the following files

- src
  - routes
    - _module.svelte
    - home
      - index.svelte

```javascript
  export const router = createRouter({
    routes,
    urlRewrite: {
      toExternal: (url) => url.startsWith('/app') ? url : '/app' + url,
      toInternal: (url) => url.replace(/^\/app/, '') || "/home"
    }
  })
```

When I visit http://localhost:3000/app/home and also everytime I refresh, during a fraction of second it displays the 404.

I also noticed that if I were to have

- src
  - routes
    - _module.svelte
    - home
      - index.svelte
    - app
      - home
        - index.svelte

Then instead it would render for a fraction of second routes/app/home/index

### Reproduction

**Routes**
- src
  - routes
    - _module.svelte
    - home
      - index.svelte

**App.svelte**
```javascript
<script context="module">
  import {Router, createRouter} from '@roxi/routify'
  import routes from '../.routify/routes.default.js'

  export const router = createRouter({
    routes,
    urlRewrite: {
      toExternal: (url) => url.startsWith('/app') ? url : '/app' + url,
      toInternal: (url) => url.replace(/^\/app/, '') || "/home"
    }
  })
</script>

<Router {router}/>
```

Visit http://localhost/app/home and refresh. During a fraction of second it displays the 404.

### System Info

```shell
Mac OS
Ruby on Rails
vite-ruby
3.0.0-next.216
```

**Comment by ghost** [comment]
@jakobrosenberg 

Not sure if this is ok, but I would like to attract your attention on this bug request :) I would like to report it is still present as of 3.0.0-next.218

**Comment by jakobrosenberg** [comment]
That's perfectly okay, @james-em . Even encouraged 😂

I'll have a look at this.

**Comment by jakobrosenberg** [comment]
I seem unable to reproduce this issue.

In which of the following do you experience the issue?
- dev without ssr
- dev with ssr
- production without ssr
- production with ssr

**Comment by ghost** [comment]
> I seem unable to reproduce this issue.
> 
> In which of the following do you experience the issue?
> 
> * dev without ssr
> * dev with ssr
> * production without ssr
> * production with ssr

Sorry for the delay. I took the time to investigate further and while trying to make a small reproductible exemple, I ended up understanding what was going on.

I will try to do my best to explain it the clearest way as possible:

Let's say I have an app with a backend and vite configured and app the following


app
-- frontend
---- entrypoints
------ app.js
------ there-could-be-others-but-dont-matter-here.js
---- myapp
------ .routify <-- routify build output folder
------ src
-------- App.svelte
-------- main.js
-------- routes
-------- --some routes...
svelte.config.js
vite.config.js

**Routify configuration** (vite.config.ts)
```js
Routify({
      routifyDir: "app/frontend/myapp/.routify",
      mainEntryPoint: "app/frontend/myapp/src/main.js",
      rootComponent: "app/frontend/myapp/src/App.svelte",
      routesDir: "app/frontend/myapp/src/routes",
      extensions: ['.svelte', '.html', '.md', '.svx', '.ts']
    }),
```

**Entrypoint configuration** (app/frontend/entrypoints/app.js)

We basically import routify build folder.
```
import "../myapp/.routify/routify-init.js";
```

**Compilation proccess**

`vite build` gets invoked:
1. Routify build and generates .routify folder
2. Vite checks for entrypoints and build and output files in dist folder.

** The issue now **

It seems that part of optimisations, Vite will output the javascript result in multiple smaller chunk js file as optimisation process. This seems to be the key to the issue. It's likely that components are not yet loaded as they are of another chunk being loaded and it displays a 404 in the mean time.

Adding to vite config this:

```
  build: {
    rollupOptions: {
      output: {
        inlineDynamicImports: true,
        format: 'iife',
      },
    }
  }
```

get rid of the error.

Does it help to investigate the error? If it is still needed, I will try to think of a way to replicate it in a small demo

**Comment by ghost** [comment]
@jakobrosenberg 

Here is a reproductible exemple I made. The explanation above is still worth reading:

[routify-bug.zip](https://github.com/roxiness/routify/files/14761519/routify-bug.zip)

** Instructions **

1. Unzip & Open terminal. 
2. `cd routify-bug/svelte-app`
3. `yarn install`
4. `yarn run build`
5. `cd ..`
6. `flask --app bug run` (Requires python3 / pip3 install flash)
7. Visit http://127.0.0.1:5000

Spam refresh you will see the 404

**Comment by jakobrosenberg** [comment]
Any chance you could make a minimal reproducible using the starter template, e.g. `npm init routify@latest`?

**Comment by ghost** [comment]
> Any chance you could make a minimal reproducible using the starter template, e.g. `npm init routify@latest`?

Hi,

This is already a minimal reproductive exemple and it requires a "backend" to reproduce it. I'm afraid that it wouldn't work

**Comment by jakobrosenberg** [comment]
I was able to spot the issue with `npm run dev` in your project. I'm gonna see if I can find a fix for this.

**Comment by jakobrosenberg** [comment]
Could you try this in your `main-app.js`

```javascript
// import "../main-app/.routify/routify-init";
import '../main-app/src/main.js'
```

**Comment by ghost** [comment]
> 6\. flask --app bug run

It appears to be working! Good to know then, consider this solved :)!
