### ISSUE TITLE
Vite build: missing specifier (^2.18.13)

### ISSUE THREAD

**Issue by Roger-Sa** [sveltech/svelte-filerouter#547]
Using vite v5.1.4. Builds fine with 2.18.12, but not with 2.18.13/14. 

Don't know if this is a bug or something I am doing wrong. My google-fu has come up short.

```
    "scripts": {
        "dev": "run-p dev:*",
        "dev:routify": "routify",
        "dev:vite": "vite",
        "preview": "vite preview",
        "build": "run-s build:*",
        "build:routify": "routify -b",
        "build:vite": "vite build"
    },
```

npm run dev:
`Missing "./runtime/buildRoutes" specifier in "@roxi/routify" package [plugin vite:dep-scan]`
`Missing "./hmr" specifier in "@roxi/routify" package [plugin vite:dep-scan]`

npm run build:
`[commonjs--resolver] Missing "./hmr" specifier in "@roxi/routify" package`

**Comment by jakobrosenberg** [comment]
Thanks for the heads up @Roger-Sa.

I'll post a fix for this. There's a possibility that it will require two fixes, so let me know if this first one works for you. 😊

**Comment by Roger-Sa** [comment]
> Thanks for the heads up @Roger-Sa.
> 
> I'll post a fix for this. There's a possibility that it will require two fixes, so let me know if this first one works for you. 😊

Works great! Thanks 😊

**Comment by alephpt** [comment]
For anyone who may run into this in the future - I was still getting this issue when trying to upgrade to 233, using npm v16 as a result of amazon linux 2 version control.

This may be a one-off that isn't worth worrying about considering 16 isn't even considered the lts version anymore. My solution was upgrading my ec2 instances to amazon linux 2023 and migrating everything over, and installing the newer version of node using nvm per the nodejs website.
