### ISSUE TITLE
Anchors / scroll into view

### ISSUE THREAD

**Issue by xboxfly15** [sveltech/svelte-filerouter#550]
I have been trying to get anchors to work, by that I mean externally(you're not already browsing the site) clicking a URL that has a hash at the end, to visit the website and the area scrolling into view. This doesn't seem to be apart of Routify.
I have done some digging and done my best to get it working. I am mainly using this to document so people can find a solution and I think there's 1 or 2 bugs that need fixing.

First off the bugs I think I found:
When visiting the URL, I get this error
![b1914817124512083GVidY816b 1](https://github.com/roxiness/routify/assets/19935166/6cc96828-d216-41c6-96f0-7a0445dea52f)
Relating to state being null at https://github.com/roxiness/routify/blame/d1decc0469e8191f0c6b8c25114c06da144dd07a/lib/runtime/Router/urlReflectors/Address.js#L42
I removed ".routify" to fix that issue.

I noticed when navigating forward/backwards I get a new error, that I haven't been able to solve and not sure what it relates to:
![896e681712451599dzfppe817b 1](https://github.com/roxiness/routify/assets/19935166/7eb5d777-80c8-4d13-a733-d6dafd01a045)
![7bc9181712451681J1TDSD818b 1](https://github.com/roxiness/routify/assets/19935166/90bd0e69-b8ee-4244-ae21-8c9ee4be525c)
It is the same line as the other bug, I haven't noticed anything breaking though so I continued.

I then added this code to my layout _module.svelte file
`afterUpdate(() => setTimeout(() => document.getElementById(location.hash.slice(1))?.scrollIntoView(), 500))`
Along with smooth scrolling css, this allows anchors to work and scroll into view.

Hope this helps people in the future when trying to get anchors to work and hopefully those errors can be fixed. Thank you contributors for your hard work.

**Comment by jakobrosenberg** [comment]
Thanks for filing the issue, @xboxfly15 .

Do you also see this bug if you copy paste the url into a new tab?

**Comment by xboxfly15** [comment]
Thank you! This solved all the errors and I was able to remove that snippet of code from my _module.svelte and it still scrolls into view!
