### ISSUE TITLE
Routing priority 

### ISSUE THREAD

**Issue by rafadess** [sveltech/svelte-filerouter#555]
Hey there,

Do we have documentation on how Routify resolves ambiguous routes? For example, if I have routes like:

```
/food/[fruit]
/food/apple
```

I've noticed that apple takes priority over the slug [fruit], which makes sense to me intuitively, but I haven't found this documented anywhere.

Does anyone know where I can find this information?

**Comment by jakobrosenberg** [comment]
Thanks for pointing this out. I've updated the documentation to cover the behavior. 😊

https://routify.dev/docs/guide/introduction/parameters
